package scrape

import (
	"github.com/wakeward/github-app-permissions-graph/pkg/fileio"
	"github.com/wakeward/github-app-permissions-graph/pkg/model"
)

// WriteDraftYAML writes Type B draft dependency edges.
func WriteDraftYAML(path string, edges []model.DependencyEdge) error {
	header := `# Type B (prose-scraped) dependencies - generated by cmd/scrape-prose
# Low confidence, needs_review: true. Promote confirmed edges into
# data/dependencies-manual.yaml (manual > scraped-draft > overlap in build).
`
	if edges == nil {
		edges = []model.DependencyEdge{}
	}
	return fileio.WriteYAML(path, header, edges)
}
