package render

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/wakeward/gh-app-graph/pkg/fileio"
	"github.com/wakeward/gh-app-graph/pkg/graph"
	"github.com/wakeward/gh-app-graph/pkg/model"
)

// WriteAll generates markdown documentation from resolved data.
func WriteAll(docsDir string, resolved graph.Resolved) error {
	if err := fileio.MkdirAll(docsDir); err != nil {
		return err
	}
	deps := graph.DependencyMap(resolved.Dependencies)
	files := []struct {
		name    string
		content string
	}{
		{"permissions-table.md", PermissionsTable(resolved.Permissions, deps)},
		{"permissions-graph.md", PermissionsGraph(resolved.Dependencies)},
		{"toxic-combinations.md", ToxicCombinationsDoc(resolved.ToxicCombinations)},
	}
	for _, f := range files {
		path := filepath.Join(docsDir, f.name)
		if err := fileio.Write(path, []byte(f.content)); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// PermissionsTable renders grouped markdown tables for each category.
func PermissionsTable(permissions []model.Permission, deps map[string]model.DependencyEdge) string {
	byCategory := make(map[string][]model.Permission)
	for _, p := range permissions {
		byCategory[p.Category] = append(byCategory[p.Category], p)
	}
	categories := make([]string, 0, len(byCategory))
	for c := range byCategory {
		categories = append(categories, c)
	}
	sort.Strings(categories)

	var b strings.Builder
	b.WriteString("# GitHub App permissions (draft seed)\n\n")
	b.WriteString("Generated by `cmd/build`. Permission metadata is **draft**; dependencies include Type A overlaps from octokit.\n\n")
	for _, cat := range categories {
		perms := byCategory[cat]
		sort.Slice(perms, func(i, j int) bool { return perms[i].APIKey < perms[j].APIKey })
		b.WriteString(fmt.Sprintf("## %s\n\n", titleCase(cat)))
		b.WriteString("| Permission | API key | Access | Severity | Impact plane | Doc status | Requires |\n")
		b.WriteString("|---|---|---|---|---|---|---|\n")
		for _, p := range perms {
			levels := append([]model.AccessLevelDetail(nil), p.AccessLevels...)
			sort.Slice(levels, func(i, j int) bool { return levels[i].Access < levels[j].Access })
			for _, lvl := range levels {
				req := formatRequires(deps, p.APIKey, lvl.Access)
				b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s | %s | %s | %s |\n",
					escapeCell(p.Name),
					p.APIKey,
					lvl.Access,
					lvl.Severity,
					p.ImpactPlane,
					p.DocStatus,
					escapeCell(req),
				))
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}

func formatRequires(deps map[string]model.DependencyEdge, apiKey string, access model.AccessLevel) string {
	key := apiKey + "\x00" + string(access)
	edge, ok := deps[key]
	if !ok || len(edge.Requires) == 0 {
		return "-"
	}
	parts := make([]string, 0, len(edge.Requires))
	for _, r := range edge.Requires {
		parts = append(parts, fmt.Sprintf("%s:%s", r.Permission, r.Access))
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

// PermissionsGraph renders a Mermaid flowchart of dependency edges.
func PermissionsGraph(deps []model.DependencyEdge) string {
	var b strings.Builder
	b.WriteString("# Permission dependency graph (Type A overlaps merged)\n\n")
	b.WriteString("Generated by `cmd/build`. Arrows mean \"requires\" (technical prerequisite).\n\n")
	b.WriteString("```mermaid\nflowchart LR\n")
	if len(deps) == 0 {
		b.WriteString("  empty[No dependencies recorded]\n")
	} else {
		nodeLabels := make(map[string]string)
		var edges []string
		for _, edge := range deps {
			fromID := mermaidNodeID(edge.Permission, edge.Access)
			nodeLabels[fromID] = fmt.Sprintf("%s:%s", edge.Permission, edge.Access)
			for _, req := range edge.Requires {
				toID := mermaidNodeID(req.Permission, req.Access)
				nodeLabels[toID] = fmt.Sprintf("%s:%s", req.Permission, req.Access)
				edges = append(edges, fmt.Sprintf("  %s --> %s", fromID, toID))
			}
		}
		sort.Strings(edges)
		ids := make([]string, 0, len(nodeLabels))
		for id := range nodeLabels {
			ids = append(ids, id)
		}
		sort.Strings(ids)
		for _, id := range ids {
			b.WriteString(fmt.Sprintf("  %s[\"%s\"]\n", id, nodeLabels[id]))
		}
		for _, line := range edges {
			b.WriteString(line + "\n")
		}
	}
	b.WriteString("```\n")
	return b.String()
}

func mermaidNodeID(permission string, access model.AccessLevel) string {
	id := strings.ReplaceAll(permission, "-", "_")
	return fmt.Sprintf("%s_%s", id, access)
}

// ToxicCombinationsDoc renders toxic combination rules or a placeholder.
func ToxicCombinationsDoc(combos []model.ToxicCombination) string {
	var b strings.Builder
	b.WriteString("# Toxic permission combinations\n\n")
	if len(combos) == 0 {
		b.WriteString("No toxic combinations defined yet. Run `cmd/migrate-toxic-combinations` to seed `data/toxic-combinations.yaml`.\n")
		return b.String()
	}
	b.WriteString("Generated by `cmd/build`.\n\n")
	for _, c := range combos {
		b.WriteString(fmt.Sprintf("## %s (%s)\n\n", c.Technique, c.BlastRadius))
		b.WriteString(fmt.Sprintf("- **ID:** `%s`\n", c.ID))
		grants := make([]string, 0, len(c.Permissions))
		for _, g := range c.Permissions {
			grants = append(grants, fmt.Sprintf("`%s:%s`", g.APIKey, g.Access))
		}
		b.WriteString(fmt.Sprintf("- **Permissions:** %s\n", strings.Join(grants, " + ")))
		b.WriteString(fmt.Sprintf("- **Risk:** %s\n\n", c.RiskDescription))
		if c.ExploitPath != "" {
			b.WriteString(fmt.Sprintf("**Exploit path:** %s\n\n", c.ExploitPath))
		}
	}
	return b.String()
}

func escapeCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
