package inventory

import (
	"fmt"
	"sort"
	"strings"

	"github.com/wakeward/github-app-permissions-graph/pkg/fileio"
	"github.com/wakeward/github-app-permissions-graph/pkg/model"
)

type overlapEdge struct {
	toPerm    string
	toAccess  string
	endpoints map[string]struct{}
}

// DetectOverlapDependencies derives Type A (category-overlap) edges from inv.
// For every endpoint listed under more than one permission category, each
// permission grant requires the other co-listed grants to call that endpoint.
func DetectOverlapDependencies(inv *Inventory) []model.DependencyEdge {
	// fromKey (permission+access) -> required edges keyed by toPerm+toAccess
	groups := make(map[string]map[string]*overlapEdge)

	for endpoint, grants := range inv.EndpointIndex {
		if len(grants) < 2 {
			continue
		}
		for i, from := range grants {
			fromKey := from.Permission + "\x00" + from.Access
			if groups[fromKey] == nil {
				groups[fromKey] = make(map[string]*overlapEdge)
			}
			for j, to := range grants {
				if i == j {
					continue
				}
				toKey := to.Permission + "\x00" + to.Access
				oe, ok := groups[fromKey][toKey]
				if !ok {
					oe = &overlapEdge{
						toPerm:    to.Permission,
						toAccess:  to.Access,
						endpoints: make(map[string]struct{}),
					}
					groups[fromKey][toKey] = oe
				}
				oe.endpoints[endpoint] = struct{}{}
			}
		}
	}

	type fromParts struct {
		permission string
		access     string
	}
	fromIndex := make(map[string]fromParts)
	for fromKey := range groups {
		parts := strings.Split(fromKey, "\x00")
		fromIndex[fromKey] = fromParts{permission: parts[0], access: parts[1]}
	}

	var fromKeys []string
	for k := range groups {
		fromKeys = append(fromKeys, k)
	}
	sort.Strings(fromKeys)

	out := make([]model.DependencyEdge, 0, len(fromKeys))
	for _, fromKey := range fromKeys {
		fp := fromIndex[fromKey]
		requiresMap := groups[fromKey]

		var toKeys []string
		for k := range requiresMap {
			toKeys = append(toKeys, k)
		}
		sort.Strings(toKeys)

		requires := make([]model.RequiredPermission, 0, len(toKeys))
		for _, toKey := range toKeys {
			oe := requiresMap[toKey]
			requires = append(requires, model.RequiredPermission{
				Permission: oe.toPerm,
				Access:     model.AccessLevel(oe.toAccess),
				Condition:  overlapCondition(oe.endpoints),
				Confidence: model.ConfidenceHigh,
				Type:       model.DependencyTypeCategoryOverlap,
				SourceURL:  docURLForPermission(inv, fp.permission),
			})
		}

		out = append(out, model.DependencyEdge{
			Permission: fp.permission,
			Access:     model.AccessLevel(fp.access),
			Requires:   requires,
		})
	}
	return out
}

func overlapCondition(endpoints map[string]struct{}) string {
	list := make([]string, 0, len(endpoints))
	for ep := range endpoints {
		list = append(list, ep)
	}
	sort.Strings(list)
	const maxExamples = 3
	if len(list) > maxExamples {
		return fmt.Sprintf(
			"Same endpoint co-listed under both permission categories (e.g. %s; +%d more)",
			strings.Join(list[:maxExamples], ", "),
			len(list)-maxExamples,
		)
	}
	return "Same endpoint co-listed under both permission categories: " + strings.Join(list, ", ")
}

func docURLForPermission(inv *Inventory, permission string) string {
	if inv == nil || inv.Permissions == nil {
		return ""
	}
	if p, ok := inv.Permissions[permission]; ok {
		return p.DocURL
	}
	return ""
}

// WriteOverlapYAML writes Type A dependency edges to path with a fixed header.
func WriteOverlapYAML(path string, edges []model.DependencyEdge) error {
	header := `# Type A (category-overlap) dependencies - generated by cmd/detect-overlap
# from data/generated/endpoints-inventory.json endpoint_index entries with
# len(permissions)>1. High confidence, automatable. Merged under manual edges
# in build (manual > scraped-draft > overlap).
`
	return fileio.WriteYAML(path, header, edges)
}
